---
- name: Include ./install.yml
  ansible.builtin.import_tasks: install.yml
  tags:
    - install_mysql_server
    - install

- name: Include ./configure.yml
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configure_mysql_server
    - configure
